services:
  app:
    build:
      context: .
      target: build
    command: /app/server
    volumes:
      - ./src:/app/src
    networks:
      app_network:
        aliases:
          - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/app/src
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    environment:
      - DOMAIN=${DOMAIN:-cmbqikkok0001xxoyhmoa0ls5-signal}
    depends_on:
      - app
    networks:
      - app_network
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    restart: unless-stopped

networks:
  app_network:
    name: app_network
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  caddy_logs:

# Enable Docker Swarm mode
version: '3.8'